
CREATE TABLE IF NOT EXISTS usuario(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome CHAR(50) NOT NULL,
    cpf VARCHAR(20) NOT NULL,
    id_usuario_php INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS fotos_usuario (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT UNSIGNED NOT NULL,
    caminho VARCHAR(255) NOT NULL,
    data_captura DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS login (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT UNSIGNED NOT NULL,
    data_login DATE NOT NULL,
    hora_login TIME NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);
